# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MytheresaChallenge\:
        resource: '../../src/'
    MytheresaChallenge\App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AppKernel.php'
    MytheresaChallenge\Tests\:
      resource: '../../tests'
    MytheresaChallenge\App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    MytheresaChallenge\Discount\Infrastructure\DataFixtures\:
        resource: '../../src/Discount/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    MytheresaChallenge\Price\Infrastructure\DataFixtures\:
        resource: '../../src/Price/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    MytheresaChallenge\Product\Infrastructure\DataFixtures\:
        resource: '../../src/Product/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    MytheresaChallenge\Category\Infrastructure\DataFixtures\:
        resource: '../../src/Category/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']