health_get:
  path: /health
  controller: MytheresaChallenge\App\Controller\HealthCheckController
  methods:  [GET]
  defaults:
    ignore_monitoring: true

get_products:
  path: /products
  controller: MytheresaChallenge\App\Controller\Product\GetProductsController
  methods:  [GET]
  defaults:
    ignore_monitoring: true
