doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MytheresaChallenge\Category:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/category'
                prefix: 'MytheresaChallenge\Category\Domain'
                alias: Category
            MytheresaChallenge\Product:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/product'
                prefix: 'MytheresaChallenge\Product\Domain'
                alias: Product
            MytheresaChallenge\Discount:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/discount'
                prefix: 'MytheresaChallenge\Discount\Domain'
                alias: Discount
            MytheresaChallenge\Price:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/price'
                prefix: 'MytheresaChallenge\Price\Domain'
                alias: Price

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
